config/routes.rb
Blog::Application.routes.draw do
  get "about/index"

  resources :sorts

  root :to => 'welcome#index'

  resources :articles do 
    resources :comments
  end
  match 'welcome/index' => 'welcome#index'
  match 'partshow' => 'welcome#partshow'
  match 'welcome/empty' => 'welcome#empty'
  match 'article/partshow' => 'articles#partshow'
  match 'article/empty' => 'articles#empty'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :author, :content, :date, :sort, :title
  has_many :comments, :dependent => :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :body, :commenter
end

app/models/sort.rb
class Sort < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
    @sorts = Sort.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end
  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])
    @sorts= Sort.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end
  def partshow
     @articles = Article.find(:all, :conditions => { :sort => params[:id]})
     @sorts = Sort.all
     if @articles.empty?
        redirect_to :action => 'empty'
     else
        render :index
     end
  end
  def empty
     @sorts = Sort.all
  end
  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new
    @sorts = Sort.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
    @sorts = Sort.all
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])
    @sorts = Sort.all
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])
    @sorts = Sort.all
    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create 
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment])
    redirect_to article_path(@article)
  end
  def destroy
   @article = Article.find(params[:article_id])
   @comment = @article.comments.find(params[:id])
   @comment.destroy
   redirect_to article_path(@article)
  end
end

app/controllers/sorts_controller.rb
class SortsController < ApplicationController
  # GET /sorts
  # GET /sorts.json
  def index
    @sorts = Sort.all
    @sort = Sort.new
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sorts }
    end
  end

  # GET /sorts/1
  # GET /sorts/1.json
  def show
    @sort = Sort.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @sort }
    end
  end

  # GET /sorts/new
  # GET /sorts/new.json
  def new
    @sort = Sort.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @sort }
    end
  end

  # GET /sorts/1/edit
  def edit
    @sort = Sort.find(params[:id])
  end

  # POST /sorts
  # POST /sorts.json
  def create
    @sort = Sort.new(params[:sort])
     respond_to do |format|
      if @sort.save
        format.html { redirect_to @sort, notice: 'Sort was successfully created.' }
        format.json { render json: @sort, status: :created, location: @sort }
      else
        format.html { render action: "new" }
        format.json { render json: @sort.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sorts/1
  # PUT /sorts/1.json
  def update
    @sort = Sort.find(params[:id])

    respond_to do |format|
      if @sort.update_attributes(params[:sort])
        format.html { redirect_to @sort, notice: 'Sort was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @sort.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sorts/1
  # DELETE /sorts/1.json
  def destroy
    @sort = Sort.find(params[:id])
    @sort.destroy

    respond_to do |format|
      format.html { redirect_to sorts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all
    @sorts = Sort.all
    respond_to do |format|
      format.html
      format.json{ render json: @articles}
    end  
  end
  
  def partshow
   @articles = Article.find(:all, :conditions => { :sort => params[:id] })
   @sorts = Sort.all
   if @articles.empty?
      redirect_to :action =>'empty'
   else
      render :index
   end
  end
 
  def empty
    @sorts = Sort.all
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sorts_helper.rb
module SortsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<div class="content_show">
  <p>这是一个个人的空间，你可以在这里记录下你生活的每个点滴</p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>
    <%= f.text_field :title %>
  </h1>
  <div class="message">
    Author:
    <%= f.text_field :author %>
    <%= f.hidden_field :date %>
  </div>
  <div class="field">
    <%= f.text_area :content %>
  </div>
   <p>
    <b>Sort:</b>
   <%= select("article","sort",@sorts.collect{|t|[t.name,t.id]})%>
  </p>
  <div class="actions" id="show_action">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="content_show">

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>
</div>

app/views/articles/empty.html.erb
<div class="content">
 <div class="content_left" id="con_left">
  <p><span>当前位置:</span>all articles</p>
    <div class="article_list" id="empty_warn">
       sorry donnt exist!!
    </div>
 </div>
 <div class="content_right">
    <div class="write_article">
      <%= link_to 'New Article', new_article_path %>
    </div>
    <div class="typelist" id="type_login">
       <ul>
             <li><%= link_to 'all articles',articles_path %></li>
          <% @sorts.each do |t|%>
             <li>
                <%= link_to t.name, { :controller => 'articles', :action => 'partshow', :id =>t }%>
             </li>
          <% end %>
             <li>
              <%= link_to 'Manage Sort', sorts_path %>
             </li>
       </ul>
    </div>
 </div>
</div>

</div>

app/views/articles/index.html.erb
<div class="content">
 <div class="content_left" id="con_left">
  <p><span>当前位置:</span>all articles</p>
    <% @articles.each do |article| %>
    <div class="article_list">
        <%= link_to article.title,article %>
        <span><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        <span><%= link_to 'Edit', edit_article_path(article) %></span>
        <span><%= article.date %></span>
    </div>
<% end %>
 </div>
 <div class="content_right">
    <div class="write_article">
      <%= link_to 'New Article', new_article_path %>
    </div>
    <div class="typelist" id="type_login">
       <ul>
             <li><%= link_to 'all articles',articles_path %></li>
          <% @sorts.each do |t|%>
             <li>
                <%= link_to t.name, { :controller => 'articles', :action => 'partshow', :id =>t }%>
             </li>
          <% end %>
             <li>
              <%= link_to 'Manage Sort', sorts_path %>
             </li>
       </ul>
    </div>
 </div>
</div>

</div>

app/views/articles/new.html.erb
<div class="content_show">
   <%= render 'form' %>
   <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="content_show">
   <p>
    <b>Sort:</b>
    <%= Sort.find_by_id(@article.sort).name%>
  </p>
  <p id="notice"><%= notice %></p>
  <h1>
    <%= @article.title %>
  </h1>
  <div class="message">
    Author:
    <%= @article.author %>
    Date:
    <%= @article.date %>
  </div>

  <div class="article_content">
    <%= @article.content %>
  </div>

  <% @article.comments.each do |comment|%>
   <div class="comments">
     <span class="commenter">
       <%= comment.commenter%>:
     </span>
     <span class="comment_body">
        <%= comment.body %>
     </span>
     <span class="destroy_comment">
        <%= link_to "delete" ,[comment.article, comment], method: :delete, data: { confirm: 'Are you sure?'}%>
     </span>
    </div>
  <% end %>

  <div class="add_comment">
     <%= form_for([@article, @article.comments.build]) do |f|%>
       <div class="field">
         <%= f.hidden_field :commenter%>
       </div>
       <div class="field">
          <%= f.text_area :body%>
       </div>
       <div class="action" id="show_action">
           <%= f.submit %>
       </div>
     <% end %>
  </div>

  <%= link_to 'Edit', edit_article_path(@article) %> |
  <%= link_to 'Back', articles_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="header">
	  <div class="header_main">
	    <h1>自知网</h1>
	    <div class="sign">寥寥心底事，天涯各自知~</div>
	    <span><%= link_to 'Index',welcome_index_path %></span>
	    <span><%= link_to 'About',about_index_path %></span>
	  </div>
    </div>
    <%= yield %>
  <footer>
      <p>© Company 2013</p>
  </footer>


</body>
</html>

app/views/sorts/_form.html.erb
<%= form_for(@sort) do |f| %>
  <% if @sort.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sort.errors.count, "error") %> prohibited this sort from being saved:</h2>

      <ul>
      <% @sort.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
   
    <%= f.text_field :name %>
  </div>
  <div class="actions" id="add_sort_btn">
    <%= f.submit %>
  </div>
<% end %>

app/views/sorts/edit.html.erb
<h1>Editing sort</h1>

<%= render 'form' %>

<%= link_to 'Show', @sort %> |
<%= link_to 'Back', sorts_path %>

app/views/sorts/index.html.erb
<div class="content_show">
  <div class="add_sort">
    <%= render 'form' %>
    <%= link_to 'Manage articles', articles_path%>
  </div>
  <ol class="sort_list">
    <% @sorts.each do |sort| %>
        <li>
          <%= sort.name %>
          <span><%= link_to 'Edit', edit_sort_path(sort) %></span>
          <span><%= link_to 'Destroy', sort, method: :delete, data: { confirm: 'Are you sure?' } %><span>
        </li>
    <% end %>
</ol>

</div>

app/views/sorts/new.html.erb
<h1>New sort</h1>

<%= render 'form' %>

<%= link_to 'Back', sorts_path %>

app/views/sorts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @sort.name %>
</p>


<%= link_to 'Edit', edit_sort_path(@sort) %> |
<%= link_to 'Back', sorts_path %>

app/views/welcome/empty.html.erb
<div class="content">
 <div class="content_left">
    <p>Sorry articles you find don't exist</p>
 </div>
 <div class="content_right">
    <div class="regist_login">
       <span class="regist"><%= link_to 'regist',articles_path  %></span>
       <span class="login"><%= link_to 'login',articles_path %><span>
    </div>
    <div class="typelist">
       <ul>
             <li><%= link_to 'all articles',welcome_index_path %></li>
          <% @sorts.each do |t|%>
             <li>
                <%= link_to t.name, { :controller => 'welcome', :action => 'partshow', :id =>t }%>
             </li>
          <% end %>
       </ul>
    </div>
 </div>
</div>

app/views/welcome/index.html.erb
<div class="content">
 <div class="content_left">
   <% @articles.each do |article|%>
     <div class="article_contents">
        <p class="art_title"><%=link_to article.title,article %><span>date:<%= article.date %></span><span>author:<%= article.author %></span></p>
        <div class="art_content"><%= article.content %></div>
        <div class="show_detail">
          <%=link_to '+ show detail', article %>
        </div>
     </div>
   <% end %>
 </div>
 <div class="content_right">
   <div class="regist_login">
      <span class="regist"><%= link_to 'regist',articles_path  %></span>
      <span class="login"><%= link_to 'login',articles_path  %></span>
   </div>
   <div class="typelist">
     <ul>
           <li><%= link_to 'all articles',welcome_index_path %></li>
        <% @sorts.each do |t|%>
           <li>
             <%= link_to t.name, { :controller => 'welcome', :action => 'partshow', :id =>t} %>
           </li>
        <% end %>
     </ul>
   </div>
 </div>
</div>